
# Paths are relative to low_pt_gnn_pipeline directory
input_dir: data/graph_constructed_latent  
stage_dir: data/gnn_stage/ 
project: MinimalGNN_Test 
accelerator: gpu       #set to "cpu" when running small local experiments..
devices: -1
nodes: 1
logger: false  

data_split: [8, 1, 1]  # trainset, valset, testset  # [training, validation, testing] 


# Model architecture parameters
edge_cut: 0.5  # Threshold for edge classification (0-1)
undirected: True
undirected_message_passing: True
node_features: [r, phi, z] 
node_scales: [1000, 3.14, 1000]  
hidden: 32  # 128 
n_graph_iters: 4  #  8
nb_node_layer: 2
nb_edge_layer: 2
emb_channels: 0
layernorm: True
batchnorm: False
aggregation: [sum, mean, max]  # Aggregation methods  in message 
hidden_activation: SiLU
output_activation: Tanh

# Training parameters
batch_size: 64                # 64 fits on GPU   ( will depend on graph size and GPU memory)
num_workers: [8, 8, 0]        # Workers for [train, val, test] dataloaders.   (current bottle neck next time, set to 16 ) 

max_epochs: 25
warmup: 2       #lineair increse from o to lr over warup epoch 
lr: 0.001          # find on initial data ~ 0.001
factor: 0.8  
patience: 3
log_every_n_steps: 1  # Log loss
check_val_every_n_epoch: 1  # Run validation every N epochs 

