
# Paths are relative to low_pt_gnn_pipeline directory
input_dir: data/graph_constructed_latent  
stage_dir: data/gnn_stage/ 
project: low_pt_GNN_20_mixed
accelerator: cuda      #cpu vs cuda 
devices: 1             
nodes: 1
logger: false  
use_wandb: true  # Enable W&B tracking
wandb_entity: bart_kuipers-nikhef  # W&B entity/username
wandb_log_every_n_batches: 500

data_split: [96000, 900, 900]  # [training, validation, testing] 

# Model architecture parameters
edge_cut: 0.5  # Threshold for edge classification (0-1)
undirected: True
undirected_message_passing: True
node_features: [hit_r, hit_phi, hit_z]          #FULL : [hit_r, hit_phi, hit_z, hit_t]   
node_scales: [1000, 3.14, 500]                  #full : [1000, 3.14, 500, 2000]

hidden: 64 # 128 
n_graph_iters: 8 #  8
nb_node_layer: 2
nb_edge_layer: 2
layernorm: True
batchnorm: True
aggregation: [sum, mean, max, std]  # Aggregation methods  in message 
hidden_activation: SiLU
output_activation: Tanh

# Training parameters
# batch_size: Hardcoded to 1 in ACORN (full-event training, one graph at a time)
num_workers: [8, 8, 0]        # Workers [train, val, test] 8 seems fine for this gpu for now
scheduler: ReduceLROnPlateau  # Reduce LR only when val_loss doesn't improve
check_val_every_n_epoch: 1  # Run validation every N epochs
accumulate_grad_batches: 1 # Effective batch size: accumulate gradients over N graphs before weight update

max_epochs: 50
warmup: 1          #lineair increse from o to lr over warup epoch
lr: 0.001          # ~ 0.001
factor: 0.5
patience: 0     # Reduce LR after val_loss hasn't improved for this many partial epochs
early_stopping_patience: 3  # Stop training after val_loss hasn't improved for this many epoch farctions 
log_every_n_steps: 1  # Log loss
val_check_interval: 0.4  # Check validation every 20% of epoch for large datasets



# Class imbalance handling
pos_weight: 1  # Adjust based on your class imbalance ratio 

