_wandb:
    value:
        cli_version: 0.23.1
        e:
            btuotooa7icsglohhugc14a8mek3sb7v:
                codePath: low_pt_gnn_pipeline/train_myGNN.py
                codePathLocal: train_myGNN.py
                cpu_count: 128
                cpu_count_logical: 256
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "67108864"
                        used: "16384"
                email: bart-kuipers@hotmail.nl
                executable: /data/alice/bkuipers/miniconda3/envs/acorn/bin/python
                git:
                    commit: a9f6b4cbaebb1e56d494ca15ab7a083bee2eb36e
                    remote: https://github.com/BartKuipers-00/ML_ACTS.git
                gpu: NVIDIA L40S
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-569990fd-2b62-0adb-f587-bbb820db7247
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-5faa433c-644c-d0cd-7786-8cda7f2ab56c
                host: wn-pijl-003.nikhef.nl
                memory:
                    total: "1216727126016"
                os: Linux-6.1.0-40-amd64-x86_64-with-glibc2.34
                program: /data/alice/bkuipers/low_pt_gnn_pipeline/train_myGNN.py
                python: CPython 3.10.19
                root: .
                startedAt: "2026-01-14T13:51:03.430765Z"
                writerId: btuotooa7icsglohhugc14a8mek3sb7v
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 9
                - 53
                - 77
                - 103
            "2":
                - 1
                - 5
                - 9
                - 53
                - 77
                - 103
            "3":
                - 7
                - 16
                - 66
            "4": 3.10.19
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
accelerator:
    value: cuda
aggregation:
    value:
        - sum
        - mean
        - max
batchnorm:
    value: false
check_val_every_n_epoch:
    value: 1
data_split:
    value:
        - 9000
        - 500
        - 500
devices:
    value: 1
edge_cut:
    value: 0.5
edge_net_recurrent:
    value: true
emb_channels:
    value: 0
factor:
    value: 0.5
hidden:
    value: 32
hidden_activation:
    value: SiLU
input_dir:
    value: data/graph_constructed_latent
layernorm:
    value: true
log_every_n_steps:
    value: 1
logger:
    value: false
lr:
    value: 0.001
max_epochs:
    value: 50
n_graph_iters:
    value: 4
nb_edge_layer:
    value: 2
nb_node_layer:
    value: 2
node_features:
    value:
        - hit_r
        - hit_phi
        - hit_z
node_net_recurrent:
    value: true
node_scales:
    value:
        - 1000
        - 3.14
        - 1000
nodes:
    value: 1
num_workers:
    value:
        - 8
        - 8
        - 0
output_activation:
    value: Tanh
patience:
    value: 2
pos_weight:
    value: 1
project:
    value: MinimalGNN_Test
scheduler:
    value: ReduceLROnPlateau
stage_dir:
    value: data/gnn_stage/
track_running_stats:
    value: false
undirected:
    value: true
undirected_message_passing:
    value: true
use_wandb:
    value: true
wandb_entity:
    value: bart_kuipers-nikhef
wandb_log_every_n_batches:
    value: 10
warmup:
    value: 0
