_wandb:
    value:
        cli_version: 0.24.0
        e:
            l2ii2lp6k7oqx7a6gml6rkhrz6k1g8c5:
                cpu_count: 32
                cpu_count_logical: 32
                disk:
                    /:
                        total: "67049664512"
                        used: "8919838720"
                email: bart-kuipers@hotmail.nl
                executable: /data/alice/bkuipers/miniconda3/bin/python
                git:
                    commit: a9f6b4cbaebb1e56d494ca15ab7a083bee2eb36e
                    remote: https://github.com/BartKuipers-00/ML_ACTS.git
                host: stbc-i1.nikhef.nl
                memory:
                    total: "269446873088"
                os: Linux-5.14.0-611.9.1.el9_7.x86_64-x86_64-with-glibc2.34
                program: <stdin>
                python: CPython 3.13.11
                root: /data/alice/bkuipers
                startedAt: "2026-01-14T12:30:38.312250Z"
                writerId: l2ii2lp6k7oqx7a6gml6rkhrz6k1g8c5
        m: []
        python_version: 3.13.11
        t:
            "3":
                - 2
                - 13
            "4": 3.13.11
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
